# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-xsk-cf"
    version = "#{XSKVersion}#"

[stack]
id = "com.sap.kneo.xsk"
build-image = "#{DOCKER_IMAGE_PREFIX}buildpacks-stack-build-xsk-cf:#{XSKVersion}#"
run-image = "#{DOCKER_IMAGE_PREFIX}buildpacks-stack-run-xsk-cf:#{XSKVersion}#"
